LOCAL_PATH := $(call my-dir)

# Install GMail
include $(CLEAR_VARS)
LOCAL_MODULE := GMail
LOCAL_SRC_FILES := GMail/GMail.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Email Exchange Exchange2
include $(BUILD_PREBUILT)
